### PR TITLE
Weakened RealFloat constraints in Data.Complex

### PR DESCRIPTION
**Pull request by RyanGlScott**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This incorporates a change in `base-4.8.0.0` in which several functions from `Data.Complex` had their type signature constraints weakened from `RealFloat` to something like `Floating` (or perhaps no constraint at all). I also added a `typediff` check for `Data.Complex.Compat`, since these changes to `base` changed the exposed type signatures.

**Comment by RyanGlScott** [comment]
Argh, I forgot that in `base-4.3.0.0`, pattern-matching a `Complex` value requires a `RealFloat` constraint due to `DatatypeContexts`, so these changes could only be backported back to `base-4.4.0.0`.

In that case, I'm not sure how to handle the `typediff` check for `Data.Complex.Compat`, since the type signatures must necessarily be different on different versions of `base`. I suppose one workaround would be to integrate the `typediff` checks into the test suite so that `MIN_VERSION_base(4,4,0)` could be used to conditionally test the output of `typediff`.

@sol, what are your thoughts?

**Comment by sol** [comment]
Regarding `typediff`, we can of course special case things in the executable.  The complicated thing is that we have to make a proper release of `typediff` before we can use it.  What I do for testing things on a branch is to temporarily check in a built `typediff` executable and invoke that.  Once everything looks good and before I merge to `master` I upload the `typediff` binary to GitHub.

Regarding this change in general, if I understand it correctly we make some functions more general by removing constraints, right?  I'm a little bit on the fence with this change.  As I understand it it's possible to write backward compatible code even without using `Data.Complex.Compat`, by just always requiring the constraints, even with the latest version of base.  Unless there is real world demand for this change I would consider to skip it.  WDYT?

**Comment by RyanGlScott** [comment]
Yeah, I believe this change was prompted by the introduction of the [`-f-warn-redundant-constraints`](https://phabricator.haskell.org/rGHCc409b6f30373535b6eed92e55d4695688d32be9e) flag. (similarly, `Ratio` will have its `Integral` constraints removed in GHC 7.12). You could just require all of your `Complex`-interfacing code to have `RealFloat` constraints, but that does preclude the ability to use `Complex` as a [dumb data type](https://www.youtube.com/watch?v=hIZxTQP1ifo), or to use `Complex` with data types other than `Double` or `Float`.

I suppose it comes down to how easily we could test for it. My idea was not to change `typediff` at all, but to use something from the `process` library to run `typediff` in a shell-script-esque fashion, then compare the results with a reference file (does `hspec` have something similar to [`tasty-golden`](http://hackage.haskell.org/package/tasty-golden)?)

**Comment by soenkehahn** [comment]
I wonder if it wouldn't be easier to use `{-# OPTIONS_GHC -fno-warn-redundant-constraints #-}` in that case. That would also result in backwards-compatible `-Wall`-sane code, wouldn't it?

**Comment by RyanGlScott** [comment]
Unfortunately, `-fno-warn-redundant-constraints` won't be introduced until GHC 7.12, so that's not a feasible option at the moment.

**Comment by RyanGlScott** [comment]
Whoops, I think I misunderstood what you meant. You were giving advice on how to make warnings go _away_, not to make them appear. In that case, we don't have to worry about that yet, since `-Wall` won't start complaining about redundant constraints until GHC 7.12.

Admittedly, I wouldn't be too torn up about not getting this change in, but I could foresee cases where a non-`RealFloat`-based `Complex` could come in handy (e.g., taking the `conjugate` of a `Complex Int`). Either way, the testing would need to improve before this can become a reality.

I'll file a separate issue for the changes that would need to be made to `typediff` and/or the test suite.

**Comment by RyanGlScott** [comment]
I've pulled in the changes to the test suite, which now allow me to use a `!(MIN_VERSION_base(4,4,0))` check to exclude `Data.Complex.Compat` from the tests on `base-4.3`.

**Pull request merged**
