### PR TITLE
Test more versions of GHC on CI

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
@RyanGlScott are you ok with renaming `master` to `main`?

`7.2.1` seems to be failing because of some `SafeHaskell` issue.  This is something we might want to fix, if possible.

**Comment by sol** [comment]
Same for `7.4.1`, `SafeHaskell`.  I disabled `fail-fast` for now, so that we see which minor versions have issue.

All the versions that were tested on Travis work fine (I had a good build for them before https://github.com/haskell-compat/base-compat/actions/runs/526141035).

**Comment by sol** [comment]
I opened https://github.com/haskell-compat/base-compat/pull/72.  It tests the versions of GHC that we had on Travis + it's ready to merge.  This PR enables more GHCs and can be considered separately.

**Comment by RyanGlScott** [comment]
If I recall correctly, the build failures all concern the `base-compat-batteries` package in particular. Before #65, when I gave up on the idea of trying to maintain CI for every minor release of GHC, I maintained [this collection of hacks](https://github.com/haskell-compat/base-compat/issues/65#issuecomment-566665746) to support particular minor releases of GHC. It's likely that many of the issues you encounter here were also documented in that collection of hacks.

**Pull request closed without merging**
