### PR TITLE
enable bang patterns

### PR DESCRIPTION
**Pull request by chessai**
enables bang patterns when building ($!), had this fail to build because of it

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Out of curiosity, how are you observing this build failure? I haven't noticed any trouble building this on Travis.

That being said, it's somewhat of a miracle that this code _does_ work without bang patterns on GHC 8.2 and 8.4. (I think it's ultimately due to [this old GHC bug](https://ghc.haskell.org/trac/ghc/ticket/14588).)

**Comment by RyanGlScott** [comment]
> I was building it using ghc861 on the 8.6 branch of ghc, with the following commit, made 2 days ago: [ghc/ghc@2e1df7c](https://github.com/ghc/ghc/commit/2e1df7c1556fc2fb6f7449ae07a382c57a0a536c)

That's quite bizarre. I have the same branch built as well, yet I have no trouble building `base-compat` with it...

In any case, this code _should_ require `BangPatterns` morally, so I'll go ahead and merge this. Is this something which deserves a new release? If so, please shout.

**Comment by chessai** [comment]
If you could make a new release, that would be very useful! Whenever you have time, thank you!

**Comment by RyanGlScott** [comment]
I've uploaded [`base-compat-0.10.5`](http://hackage.haskell.org/package/base-compat-0.10.5) to Hackage.

**Comment by chessai** [comment]
Thanks!

**Pull request merged**
