### PR TITLE
Oleg experiments

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
I don't know, why it doesn't work :( I'd try changing `typecheck` to look for particular file (i.e. `getEnv "HOME"`), maybe that would shred light.

**Comment by RyanGlScott** [comment]
Darn, I was hoping I was overlooking something obvious here. I greatly appreciate your help nonetheless!

**Comment by RyanGlScott** [comment]
I've figured out what is going on here. Recall the error message that gets thrown:

```
       uncaught exception: IOException of type NoSuchThing
       cabal: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

I was so caught up in thinking that `typediff` was the culprit that I didn't notice that it's actually _`cabal`_ that's misbehaving! More specifically, `cabal` is not the `PATH`, and since the `base-compat` test suite invokes `cabal new-repl` directly at various points, it complains that `cabal` does not exist. The `haskell-ci`–generated `.travis.yml` file on `master` puts `cabal` directly on the `PATH`, whereas the `.travis.yml` file on the `travis-experiments` branch does not, which is why this problem only appeared recently.

I suppose we could fix this by just changing `travis.yml.patch` to augment the `PATH` with `/opt/ghc/bin`, the directory that `cabal` lives in. I've done so in commit 37593bfb2d097107a3c1cdb767db38ae098bef8d, and it seems to work well enough.

On a more general note, is there a reason that `haskell-ci` doesn't add `/opt/ghc/bin` to the `PATH` anymore?

**Comment by phadej** [comment]
Exactly to catch implicit calls to GHC or cabal. I’d rather put a symbolic link to cabal in ~/.local/bin then expose all the stuff in /opt/ghc/bin

**Pull request closed without merging**
