### PR TITLE
Don't depend on the unix package on HaLVM

### PR DESCRIPTION
**Pull request by elliottt**
Small cabal file tweak to make base-compat work with the HaLVM.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Does HaLVM use a version of `base` that includes `System.Posix.Env`? If not, then don't we need to [change `System.Environment.Compat`](https://github.com/haskell-compat/base-compat/blob/15e25e4f0162c05c59c8987d0ede45ccfe6f2cf7/src/System/Environment/Compat.hs#L21-L28) as well?

**Comment by elliottt** [comment]
When does `System.Posix.Env` show up in `base`? If I'm looking in the right place, it's not included in the version of `base` that we ship, though the `System.Posix.Internal` and `System.Posix.Types` modules are (we do some amount of work to emulate a POSIX environment).

**Comment by RyanGlScott** [comment]
`System.Posix.Env` is normally provided by the `unix` package, so simply disabling `unix` in the `.cabal` file would mean that `System.Posix.Env` would do the wrong thing in [these lines](https://github.com/haskell-compat/base-compat/blob/15e25e4f0162c05c59c8987d0ede45ccfe6f2cf7/src/System/Environment/Compat.hs#L21-L28):

```haskell
# ifdef mingw32_HOST_OS
import           Control.Monad
import           Foreign.C
import           Foreign.Safe
import           GHC.Windows
# else
import qualified System.Posix.Env as Posix
# endif
```

since it assumes you're using an OS with `unix` avaialble if you're not using Windows.

**Comment by elliottt** [comment]
Ah, OK. Yes, that ifdef would need to be modified to support the HaLVM correctly. I'll have a look, and modify the pull request. Thanks!

**Comment by RyanGlScott** [comment]
Resolved in 75d73ed1d9179864f41862ba67d624eb6c26d9eb.

**Pull request closed without merging**
